Feature/f tmp leg uk
Hattyot/TLDR-Bot pull request #30
Opened 2021-04-19 07:54 UTC by TheMasteredPanda

At the request of FlyingP1g I am producing this request to merge what I have written currently.

Includes the following commands:
  - bills search
  - bills info
  - divisions csearch
  - divisions cinfo
  - divisions linfo
  - divisions lsearch

2021-04-25 21:20 UTC, Hattyot requested changes
More generic initial notes:

1. add back config_example.py to keep track of all the stuff that needs to be in the config

2. update requirements with the new modules added to the bot, like matplotlib

3. Try to comply more with pep8 rules, except the line length one, that can mostly be ignored.

4. instead of being static i think it would be nice if config.LORDS_CHANNEL and other values like that could be set through a command, that part can be delayed for later though

5. try to keep track of unused variables and remove them

6. for the ukparliament please provide documentation like in the other modules

7. this is a minor thing, but sort the imports by "import x" at the top and "from y import x" at the bottom sorted by an enter, if not possible and it causes conflicts or something ignore this

8. move from json storage to mongodb

9. For lines that do get exceedingly long, like line 420 in uk_parliament cog, it would be nice to split the code into sections on seprate lines.

10. instead of leaving commands empty with a "pass" like divisions command in uk_parliament cog. Add "return await embed_maker.command_error(ctx)". It'll return help data on the command.

11. also keep track of unused imports

12. try to avoid "is" with a literal. like line 217 in uk_parliament cog

13. UKCommand class can be renamed to just UK.

14. If args in commands is None, also return "await embed_maker.command_error(ctx)" to send the user info about the command.

15. when possible, instead of establishing a new aiohttp client session, grab it from the bot "aiohttp_session = getattr(self.bot.http, '_HTTPClient__session')"

16. In the embeds, i think the "ID" value can be left out

17. This is something we should establish together, but the image creation will need to be offloaded to a separate api hosted on heroku or smth.

18. For the command_args in all the different commands, i think you should still add add a short version of the arg and provide an example for every command_arg and limits if needed.

2021-04-25 21:20 UTC, Hattyot commented on bot.py
> +    async def on_ready(self):
the default on_ready should not be overwritten. You should move it's functionality to it's own function in the Events cog and call it in Events on_ready listener.

2021-04-25 21:20 UTC, Hattyot commented on bot.py
> +    def get_parliament(self):
this function should be removed, i dont think it's needed

2021-04-25 21:20 UTC, Hattyot commented on bot.py
> +    def get_parliament_module(self):
this function should be removed, i dont think it's needed

2021-04-25 21:20 UTC, Hattyot commented on modules/ukparliament.py
> +        await self.parliament.get_bills_tracker()._poll()
if you're gonna access values of an outside class, like here, I dont think you should make it a protected value

2021-04-25 21:20 UTC, Hattyot commented on cogs/uk_parliament.py
> +Pair = namedtuple("Pair", ["enum", "max_page_num"])
what's this used for?

2021-04-25 21:20 UTC, Hattyot commented on cogs/uk_parliament.py
> +        if args['historical'] is '':
should change the is to ==

2021-04-25 21:20 UTC, Hattyot commented on cogs/uk_parliament.py
> +        embed: embeds.Embed = await embed_maker.message(ctx, description=f"**Title:** {division.get_division_title()}{next_line}**Division Outcome:** {'Passed' if did_pass else 'Not passed'} by a div
This def needs to be split into a bunch of different lines

2021-04-25 21:20 UTC, Hattyot commented on modules/ukparliament.py
> +        description = f"**ID:** {division.get_id()}{next_line}**Summary [(Link)](https://votes.parliament.uk/Votes/Lords/Division/{division.get_id()}):** {division.get_amendment_motion_notes()[0:250]
This also really needs to be split into separate lines.

2021-04-26 17:06 UTC, TheMasteredPanda commented on bot.py
> +    def get_parliament(self):
Used in the the modules script of this feature.

2021-04-26 17:06 UTC, TheMasteredPanda commented on modules/ukparliament.py
> +        await self.parliament.get_bills_tracker()._poll()
Fixed.

2021-04-26 17:08 UTC, TheMasteredPanda commented on cogs/uk_parliament.py
> +        if args['historical'] is '':
Fixed.

2021-04-26 17:08 UTC, TheMasteredPanda commented on cogs/uk_parliament.py
> +        embed: embeds.Embed = await embed_maker.message(ctx, description=f"**Title:** {division.get_division_title()}{next_line}**Division Outcome:** {'Passed' if did_pass else 'Not passed'} by a div
Done.

2021-04-26 17:08 UTC, TheMasteredPanda commented on modules/ukparliament.py
> +        description = f"**ID:** {division.get_id()}{next_line}**Summary [(Link)](https://votes.parliament.uk/Votes/Lords/Division/{division.get_id()}):** {division.get_amendment_motion_notes()[0:250]
Again. fixed.

2021-05-01 12:25 UTC, closed without merging